services:
  db:
    image: mysql:latest
    container_name: mysql-latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: kevin
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: tallermotos-education-db
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer-hydra
    restart: always
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      ADMINER_DESIGN: "hydra"
      ADMINER_SERVER: db
